### ISSUE TITLE
c3d features

### ISSUE THREAD

**Issue by TAY-985** [r-cui/ViGA#2]
could you please the c3d features of charades?

**Comment by r-cui** [comment]
Hello Tay,

In short, we extracted the C3D features of Charades-STA by ourselves, we decided not to make it available for downloading due to our limited resource of online storage, and the fact that this process can be easily replicated. 

To specify, we directly adopted the C3D model weights pre-trained on Sports1M. The extracted feature of each clip in a video was the `fc6` layer, and the clips were sampled via sliding window of `step size of 8, window size of 16`.

Our codes for this extraction were based on this repo. https://github.com/DavideA/c3d-pytorch

Thank you for this reminder, this info is now updated to the readme.


Ran
