### ISSUE TITLE
how to reproduce the scores of Charades-STA?

### ISSUE THREAD

**Issue by daidaiershidi** [r-cui/ViGA#4]
Thank you very much for your inspiring work, but I don't know why I can't reproduce the scores in the paper

-- |R@0.3 | R@0.5 | R@0.7 | mIoU
-- | -- | -- | -- | --
ViGA(I3D) | 71.21 | 45.05 | 20.27 | 44.57
ViGA-re(I3D) | 70.08 | 43.92 | 19.30 | 43.82

**Comment by zhanglong-ustc** [comment]
应该怎么处理charade-sta数据集，直接下载的数据集 总是在 torch.stack处报错

**Comment by daidaiershidi** [comment]
> 应该怎么处理charade-sta数据集，直接下载的数据集 总是在 torch.stack处报错

把hdf5拆成npy就行

**Comment by daidaiershidi** [comment]
> 应该怎么处理charade-sta数据集，直接下载的数据集 总是在 torch.stack处报错

你看看能不能跑出来论文里的分数，是不是我的配置有问题

**Comment by zhanglong-ustc** [comment]
你好，sub_activitynet_v1-3.c3d.hdf5 这个文件怎么下载呀，有人下载好了可以分享一下吗

**Comment by r-cui** [comment]
Hi daidaiershidi,

Thank you for your interest in our work. Given the limited information, we could not figure out where the problem lies, too. However, we can provide the following guess for your reference:

As far as we know, the feature of Charades-STA dataset has a lot of versions - not like ActivityNet Captions which pretty much has only one version sub_activitynet_v1-3.c3d.hdf5. To replicate our exact scores on Charades-STA, please do make sure that you prepare the data in the way that we described, rather than download elsewhere. This is what we consider the most probable reason.

Other than this, the mismatch may also due to the different randomness across the machines, which we assume you are aware of already.

Good luck,
Ran
